// <auto-generated />
using Fiap.Api.VerdeVolt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.VerdeVolt.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250612041606_CriarTabelaMatriz")]
    partial class CriarTabelaMatriz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.VerdeVolt.Models.MatrizEnergeticaModel", b =>
                {
                    b.Property<long>("MatrizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MatrizId"));

                    b.Property<int>("Biomassa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Eolica")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("GasNatural")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Hidroeletrica")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Nuclear")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Petroleo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("PorcentagemFonteRenovavel")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("Solar")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("MatrizId");

                    b.ToTable("MatrizEnergeticaVerdeVolt", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
